// skilliconsMap.js
// Map skill names to skillicons.dev icon IDs
export const skilliconsMap = {
  // Languages
  Python: "py",
  JavaScript: "js",
  Java: "java",
  "C": "c",
  "C++": "cpp",
  "C#": "cs",
  TypeScript: "ts",
  "Go (Golang)": "go",
  Ruby: "ruby",
  PHP: "php",
  Swift: "swift",
  Kotlin: "kotlin",
  Rust: "rust",
  Scala: "scala",
  // Frameworks & Libraries
  "React.js": "react",
  "Angular": "angular",
  "Vue.js": "vue",
  "Next.js": "nextjs",
  "Nuxt.js": "nuxtjs",
  "Svelte": "svelte",
  "Express.js": "express",
  "Django": "django",
  "Flask": "flask",
  "Ruby on Rails": "rails",
  "React Native": "react",
  "Flutter": "flutter",
  "Ionic": "ionic",
  "SwiftUI": "swift",
  "Jetpack Compose": "kotlin",
  "Spring Boot": "spring",
  "Laravel": "laravel",
  "ASP.NET Core": "dotnet",
  "NestJS": "nestjs",
  "TensorFlow": "tensorflow",
  "PyTorch": "pytorch",
  "Keras": "keras",
  "Scikit-learn": "sklearn",
  "Pandas": "pandas",
  "NumPy": "numpy",
  "Matplotlib": "matplotlib",
  "Bootstrap": "bootstrap",
  "Tailwind CSS": "tailwind",
  // Deployment & Hosting
  Vercel: "vercel",
  Netlify: "netlify",
  Render: "render",
  Heroku: "heroku",
  "GitHub Pages": "github",
  "Microsoft Azure App Service": "azure",
  "DigitalOcean App Platform": "digitalocean",
  // Databases
  MySQL: "mysql",
  PostgreSQL: "postgres",
  MongoDB: "mongodb",
  SQLite: "sqlite",
  CouchDB: "couchdb",
  "Firebase Realtime Database": "firebase",
  DynamoDB: "dynamodb",
  // Tools & Platforms
  GitHub: "github",
  GitLab: "gitlab",
  Docker: "docker",
  Kubernetes: "kubernetes",
    "Ionic": "ionic",
    "Keras": "keras",
    "Matplotlib": "matplotlib",
    "NumPy": "numpy",
    "Pandas": "pandas",
    CouchDB: "couchdb",
    "Travis CI": "travis",
    Travis: "travis",
    Canva: "canva",
    "Visual Studio Code (VS Code)": "vscode",
  Notion: "notion",
  "Visual Studio Code (VS Code)": "vscode",
  "IntelliJ IDEA": "idea",
  Eclipse: "eclipse",
  Git: "git",
};
